# 基础索引类型

https://github.com/facebookresearch/faiss/wiki/Faiss-indexes

## 数据准备

In [1]:
import numpy as np 

d = 512          #维数
n_data = 2000   
np.random.seed(0)

# train data
data = []
mu = 3
sigma = 0.1
for i in range(n_data):
    data.append(np.random.normal(mu, sigma, d))
data = np.array(data).astype('float32')

# query data
query = []
n_query = 10
np.random.seed(12) 
query = []
for i in range(n_query):
    query.append(np.random.normal(mu, sigma, d))
query = np.array(query).astype('float32')

In [9]:
import sys
import faiss

k=6

## 1. IndexFlatL2(精确搜索, Exact Search for L2)

一种暴力搜索方法，遍历数据库中的每一个向量与查询向量对比。

In [10]:
index = faiss.IndexFlatL2(d)
# index = faiss.index_factory(d, "Flat") # 两种定义方式
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1269 1525 1723 1160 1694   48]
 [1035  259 1279 1116 1398  879]
 [ 327  345 1401  389 1904 1992]
 [1259  112  351  804 1412 1987]
 [1666  854 1135  616   94  280]
 [ 574 1523  366  766 1046   91]
 [1945  944  244  655 1686  981]
 [ 879 1025  390  269 1115 1662]
 [ 156  154   99   31 1237  289]
 [ 427  182  375 1826  610 1384]]
[[8.61838  8.782156 8.782816 8.832029 8.837633 8.848496]
 [9.033303 9.038907 9.091705 9.15584  9.164591 9.200112]
 [8.063818 8.211029 8.306456 8.373352 8.459253 8.459892]
 [8.193894 8.211956 8.34701  8.446963 8.45299  8.45486 ]
 [8.369624 8.549444 8.704066 8.736764 8.760082 8.777319]
 [8.299072 8.432398 8.434382 8.457374 8.539217 8.562359]
 [8.615004 8.615164 8.72604  8.730943 8.762621 8.796932]
 [8.377227 8.522776 8.711159 8.724562 8.745737 8.763846]
 [8.342917 8.488056 8.655106 8.662771 8.701336 8.741287]
 [8.522164 8.575703 8.68462  8.767247 8.782909 8.850494]]


## 2. IndexFlatIP(精确搜索, Exact Search for Inner Product)

当数据库向量是标准化的，计算返回的distance就是余弦相似度。

In [11]:
index = faiss.IndexFlatIP(d)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1562   27  681  169 1262  942]
 [  27 1562  169  681 1262  942]
 [1562   27  681  169 1262  942]
 [1562   27  681  169 1262  942]
 [1562   27  681  169 1262  942]
 [1562   27  169  681 1262  942]
 [1562   27  169  681 1262 1566]
 [1562   27  681  169 1262  942]
 [  27 1562  169  681 1262  942]
 [1562   27 1262  681  169  942]]
[[4621.749  4621.5464 4619.745  4619.381  4619.177  4618.0615]
 [4637.3975 4637.288  4635.368  4635.2446 4634.881  4633.608 ]
 [4621.756  4621.4697 4619.7485 4619.5615 4619.424  4618.0186]
 [4623.6074 4623.5596 4621.3965 4621.158  4620.906  4619.838 ]
 [4625.553  4625.0645 4623.461  4623.196  4622.957  4621.337 ]
 [4628.489  4628.449  4626.491  4626.487  4625.6406 4624.6143]
 [4637.7466 4637.338  4635.3047 4635.125  4634.748  4633.0137]
 [4630.472  4630.333  4628.264  4627.9375 4627.738  4626.8965]
 [4635.7715 4635.489  4633.6904 4633.568  4632.658  4631.463 ]
 [4625.6753 4625.558  4623.454  4623.3926 4623.324  4622.2827]]


## 3. IndexHNSWFlat(Hierarchical Navigable Small World graph exploration)
返回近似结果。

In [14]:
index = faiss.IndexHNSWFlat(d,16)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1269   48 1075 1028  916  239]
 [ 259 1398  879  289  882 1927]
 [1401  389 1904  106 1623 1393]
 [1259  112  351 1987 1377  250]
 [1666   94 1212  277  581  106]
 [ 574 1523  366 1046   91  154]
 [ 944  655 1280  849  876 1337]
 [ 879 1025  390  269 1115 1831]
 [ 156  154   31  289  769 1524]
 [ 182  375 1384 1299  750    2]]
[[8.61838  8.848496 8.897978 8.916636 8.9374   8.9597  ]
 [9.038907 9.164591 9.200112 9.201884 9.220335 9.312859]
 [8.306456 8.373352 8.459253 8.546464 8.631898 8.63715 ]
 [8.193894 8.211956 8.34701  8.45486  8.473572 8.50477 ]
 [8.369624 8.760082 8.858271 8.862642 8.996922 8.998444]
 [8.299072 8.432398 8.434382 8.539217 8.562359 8.698317]
 [8.615164 8.730943 8.813985 8.861536 8.885755 8.911812]
 [8.377227 8.522776 8.711159 8.724562 8.745737 8.768602]
 [8.342917 8.488056 8.662771 8.741287 8.743608 8.770507]
 [8.575703 8.68462  8.850494 8.883733 8.90369  8.909393]]


## 4. IndexIVFFlat(倒排表搜索, Inverted file with exact post-verification)
快速入门部分介绍过。

In [15]:
nlist = 50
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(data)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1694 1740   79 1476 1795 1674]
 [ 478 1480  443 1675 1167 1554]
 [1179 1632  725  380  987 1504]
 [ 112  402  510 1937 1989 1633]
 [1212  106  472  375  151  846]
 [ 366 1046   46  911  685  444]
 [ 849 1784 1540  744   78  969]
 [ 385 1133  999 1384 1273 1363]
 [ 769  977 1091 1742  902 1868]
 [ 511  529  818  263 1179 1877]]
[[8.837633  9.122337  9.217627  9.362019  9.39345   9.396795 ]
 [9.436286  9.636714  9.707813  9.714355  9.734249  9.809814 ]
 [8.621426  8.658703  8.842339  8.862192  8.891519  8.937078 ]
 [8.211956  8.735372  8.747662  8.800873  8.917062  9.1208725]
 [8.858271  8.998444  9.041813  9.0883045 9.159481  9.169218 ]
 [8.434382  8.539217  8.630861  8.753672  8.768751  8.794859 ]
 [8.861536  8.878873  8.942963  8.944212  8.9446945 8.95914  ]
 [9.15522   9.423113  9.432117  9.465836  9.529045  9.554071 ]
 [8.743608  8.902418  9.065649  9.201052  9.223066  9.223073 ]
 [8.936615  9.077     9.152468  9.1537075 9.313195  9.314999 ]]


## 5. IndexLSH(LSH, Locality-Sensitive Hashing)
binary flat index

In [17]:
nbits = 2 * d
index = faiss.IndexLSH(d, nbits)
index.train(data)
index.add(data)
D, I = index.search(query, k)

print(I)
print(D)

[[1424  760 1043  668 1544  345]
 [1974 1436 1476   51  711   44]
 [1667 1356 1149  512 1021  309]
 [ 107  708  606  243   18  598]
 [ 541 1142 1455 1140  843  370]
 [ 193  953 1735  263 1109 1071]
 [1129 1231  123 1731  336  257]
 [ 336   70  845 1622  980  331]
 [1335  395  263  346 1206  713]
 [1395  279 1305 1160  226 1205]]
[[ 8. 10. 10. 10. 10. 10.]
 [ 7.  8.  9.  9.  9. 10.]
 [ 7.  8.  8.  9.  9.  9.]
 [ 9.  9. 10. 11. 12. 12.]
 [ 6.  6.  6.  7.  7.  8.]
 [ 8.  8.  8.  9.  9.  9.]
 [ 6.  7.  8.  8.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.]
 [ 7.  8.  8.  8.  8.  8.]
 [ 9.  9.  9. 10. 10. 10.]]


## 6. IndexScalarQuantizer(SQ量化, Scalar quantizer (SQ) in flat mode)

In [18]:
index = faiss.IndexScalarQuantizer(d, 4)
index.train(data)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1269 1723 1525 1160 1694   48]
 [1035  259 1279 1116 1398  289]
 [ 327  345 1401  389 1992 1904]
 [1259  112  351  804 1987 1412]
 [1666  854 1135  616   94  280]
 [ 574 1523  366  766 1046   91]
 [ 944 1945  244  655 1686  256]
 [ 879 1025  390  269 1115 1662]
 [ 156  154   99   31 1237  289]
 [ 427  182  375 1826  610 1384]]
[[8.623227  8.777792  8.785317  8.828824  8.83549   8.845292 ]
 [9.028506  9.037546  9.099248  9.1526165 9.16542   9.19639  ]
 [8.064029  8.21301   8.310526  8.376435  8.457833  8.462002 ]
 [8.19665   8.210531  8.346436  8.444769  8.452809  8.454114 ]
 [8.370452  8.547959  8.704323  8.733619  8.763926  8.776738 ]
 [8.29591   8.432422  8.435944  8.454732  8.542395  8.565367 ]
 [8.609016  8.612934  8.72663   8.734133  8.758857  8.797326 ]
 [8.378947  8.521084  8.711153  8.726161  8.748383  8.759655 ]
 [8.340463  8.48951   8.659344  8.664954  8.702756  8.741513 ]
 [8.520282  8.574987  8.683459  8.769213  8.7820425 8.85128  ]]


## 7. IndexPQ(PQ量化, Product quantizer (PQ) in flat mode)

In [19]:
M = 8 #必须是d的因数
nbits = 6  #只能是8， 12， 16
index = faiss.IndexPQ(d, M, nbits)
index.train(data)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

[[1000 1775  689 1063 1651  702]
 [ 243  304  532 1212 1264 1250]
 [1904  735 1810  839  492  281]
 [ 250 1307 1773  371  138  576]
 [1135 1276  250 1945 1408 1429]
 [1427  816 1314 1096 1463  896]
 [ 244  854 1081   85  218  885]
 [ 278  830  787 1176  862  892]
 [  81  855  416 1545  145  172]
 [1400  902  725  110  315 1141]]
[[5.3184814 5.33667   5.3638916 5.366333  5.3704834 5.4000244]
 [5.6835938 5.686035  5.687134  5.7489014 5.76062   5.7731934]
 [4.902588  5.0057373 5.0323486 5.036255  5.045044  5.048828 ]
 [4.844116  4.850586  4.868042  4.8946533 4.8997803 4.8999023]
 [5.279419  5.333252  5.3344727 5.3431396 5.35083   5.357422 ]
 [5.019409  5.048706  5.0942383 5.1052246 5.116455  5.157593 ]
 [5.0563965 5.0909424 5.1367188 5.1534424 5.1724854 5.199951 ]
 [5.16333   5.173706  5.2418213 5.265259  5.265869  5.274414 ]
 [5.1501465 5.2508545 5.291992  5.3186035 5.3205566 5.328369 ]
 [5.2751465 5.2772217 5.279663  5.3304443 5.350708  5.3571777]]


## 8. IndexIVFPQ(倒排表乘积量化, IVFADC (coarse quantizer+PQ on residuals))

In [ ]:
M = 8
nbits = 4
nlist = 50
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFPQ(quantizer, d, nlist, M, nbits)
index.train(data)
index.add(data)

D, I = index.search(query, k)

print(I)
print(D)

# cell-probe方法
为了加速索引过程，经常采用划分子类空间（如k-means）的方法，虽然这样无法保证最后返回的结果是完全正确的。先划分子类空间，再在部分子空间中搜索的方法，就是cell-probe方法。  
具体流程为：  
1) 数据集空间被划分为n个部分，在k-means中，表现为n个类；  
2) 每个类中的向量保存在一个倒排表中，共有n个倒排表；  
3) 查询时，选中nprobe个倒排表；  
4) 将这几个倒排表中的向量与查询向量作对比。  
在这种方法中，只需要排查数据库中的一部分向量，大约只有nprobe/n的数据，因为每个倒排表的长度并不一致（每个类中的向量个数不一定相等）。

# cell-probe粗量化
在一些索引类型中，需要一个Flat index作为粗量化器，如IndexIVFFlat,在训练的时候会将类中心保存在Flat index中，在add和search阶段，会首先判定将其落入哪个类空间。在search阶段，nprobe参数需要调整以权衡检索精度与检索速度。  
实验表明，对高维数据，需要维持比较高的nprobe数值才能保证精度。

# 与LSH的优劣
LSH也是一种cell-probe方法，与其相比，LSH有一下一点不足：  
1）LSH需要大量的哈希方程，会带来额外的内存开销；  
2）哈希函数不适合输入数据。